language: node_js
node_js: node
before_install: 
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: Cscw0wyJDEUKBqVrMVLlpsbzCq0uFlvsSE6V02iJR+abPqRb5oqMMjHHlw3262mkShYxs3J1uExUOV+rPwpz9xvVVAeVOJcRHPSLk7Hmht526lJSAdhisON59q1oqIW3RQBNE8PLPGVMZCQzntbMBHaQlSXi5+sGaf617jFQA7Ah7ZaQnaFwA1ovLdlFPaLhOzw1xSrk6Zh/qErXFbtSMnX9AWvSf99tzr7PMoUbrsN0Rp1cV6fiia5hLZm5hUD/WTDdL9PuErB5wYJS0m73UyPszCSHCt7Il2GtRbvQa1FgZRAXPT+GxFO6CoqGjBJnWFNswIxw3uiiHaVozwF1YzvNtjo13Dog1P0YunipZYlPVBKrQvW4MpfMPwB44mSmyuPw8TVSdRFwUvKovYFRKa6o/jIy/VC4IbGV52rUVpjUyag1bRmlBQTRxNUrWymMBh9ME8wdP09LCk8KfPEjbBX7rQcfRG5vMDFzcD2O2zZqwzVwESGQ9k3UM3cny7RGviyjS31Mz14wjRiXptAwlqdAIKfhf3VqxF9bkvdu6qItxpjCyl4IkGK8A1eCOzjzap4P5BtAoMlRQEDMuR/1SkUm+3XV7EvLRh17pt/bXy3EyUuh3VGyo3QLHr1QKA8ig0CyZ4FoDtrdV7Z4F3df8qcwWPqVt5BW0N0CZjWALds=
  app: abastify-fe
